version: 2
updates:
  - package-ecosystem: "bundler"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
        - "rubocop*"
      rubocop:
        patterns:
        - "rubocop*"
    directory: "/"
    schedule:
      day: "monday"
      time: "01:00"
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "monday"
      time: "01:00"
      interval: "weekly"
    cooldown:
      default-days: 7
