aides_etat:
  name: Plateforme Aides d’État
  description: "Aides d’État collecte et partage de manière sécurisée les données sur les aides d'État et les aides de minimis octroyées aux entreprises."
  provider: "dge"
  kind: 'service'
  link: "https://aides-etat.gouv.fr/feedme-with-valid-url"
  cgu_link: "https://aides-etat.gouv.fr/cgu"
  access_link: "https://aides-etat.gouv.fr/tokens/%{external_provider_id}"
  public: true
  support_email: "holy.rasandy@finances.gouv.fr"
  blocks:
    - name: "contacts"
