api_mobilic:
  name: API Mobilic
  description: "Mobilic est la plateforme gouvernementale qui permet de simplifier le suivi du temps de travail dans le transport routier léger et le déménagement afin de lutter contre le travail illégal."
  provider: "mtes"
  kind: 'api'
  link: "https://www.data.gouv.fr/fr/dataservices/api-mobilic/"
  cgu_link: "https://cgu-api.mobilic.beta.gouv.fr/"
  access_link: "https://api-mobilic.gouv.fr/tokens/%{external_provider_id}"
  public: true
  support_email: contact@mobilic.beta.gouv.fr
  blocks:
    - name: "basic_infos"
    - name: "personal_data"
    - name: "scopes"
    - name: "contacts"
  scopes:
    - name: "J’envoie les données d’enregistrement d’une mission"
      value: "donnees_enregistrement_mission"
      group: "J'envoie des données à Mobilic"
      link: "https://developers.mobilic.beta.gouv.fr/workflow-a-respecter"
    - name: "Je m'engage à la sécurisation des données"
      value: "securisation_donnees"
      group: "J'envoie des données à Mobilic"
    - name: "J’envoie les données relatives à la modification et à la validation par le salarié"
      value: "donnees_modification_salarie"
      group: "J'envoie des données à Mobilic"
    - name: "J’intègre le code à réponse rapide de contrôle Mobilic dans mon logiciel"
      value: "code_reponse_rapide"
      group: "J'envoie des données à Mobilic"
    - name: "J’envoie les données relatives à la modification et à la validation par le gestionnaire"
      value: "donnees_modification_gestionnaire"
      group: "J'envoie des données à Mobilic"
    - name: "Je confirme informer mes clients sur la nécessité de créer un compte Mobilic"
      value: "information_clients"
      group: "J'envoie des données à Mobilic"
    - name: "Je récupère les données contenues dans Mobilic"
      value: "recuperation_donnees_mobilic"
      group: "Je récupère les données contenues dans Mobilic"
