api_scolarite:
  name: "API scolarité de l’élève"
  description: "Statut scolarisé et statut boursier d’un élève du primaire, collège ou lycée."
  provider: "menj"
  kind: 'api'
  link: "https://api.gouv.fr/les-api/api-scolarite-ministere-education-nationale"
  cgu_link: "/cgus/cgu_api_scolarite.pdf"
  support_email: "api-sco-eleve_contacts@education.gouv.fr"
  public: true
  blocks:
    - name: "basic_infos"
    - name: "personal_data"
    - name: "legal"
    - name: "scopes"
    - name: "contacts"
  scopes:
    - name: 'Statut scolarité'
      value: 'men_statut_scolarite'
    - name: 'Statut boursier'
      value: 'men_statut_boursier'
    - name: 'Échelon de la bourse'
      value: 'men_echelon_bourse'

api_gfe_echange_collectivites:
  name: "GFE Échanges Collectivités"
  description: "Permet aux collectivités d’échanger des flux XML avec GFE"
  provider: "menj"
  kind: 'api'
  link: "https://api.education.gouv.fr"
  cgu_link: "https://api.education.gouv.fr/api-gfe-echanges-collectivites"
  support_email: "dsi.diffusion-gfe@ac-clermont.fr"
  public: true
  blocks:
    - name: "basic_infos"
    - name: "personal_data"
    - name: "legal"
    - name: "contacts"

api_gfe_echange_editeurs_restauration:
  name: "GFE Échanges Éditeurs Restauration"
  description: "Permet aux éditeurs de transmettre leur flux XML quotidien contenant les repas consommés ou réservés des élèves"
  provider: "menj"
  kind: 'api'
  link: "https://api.education.gouv.fr"
  cgu_link: "https://api.education.gouv.fr/api-gfe-echanges-editeurs-restauration"
  support_email: "dsi.diffusion-gfe@ac-clermont.fr"
  public: true
  blocks:
    - name: "basic_infos"
    - name: "personal_data"
    - name: "legal"
    - name: "contacts"

api_inser_jeunes_sup:
    name: API Exposition InserJeunes InserSup
    description: Exposition au grand public et aux futurs élèves des indicateurs clés sur les formations. Ces indicateurs ont vocation à éclairer sur les chances d’employabilité des élèves en sortie de formation, mais aussi sur les possibilités de poursuite d’études. Les données sont exposées sur différentes plateformes partenaires telles que ParcourSup, AFFELNET ou l’ONISEP.
    provider: "menj"
    link: https://documentation-api-exposition-inser-jeunes-sup.phm.education.gouv.fr
    cgu_link: https://api.education.gouv.fr/?api_portal=1&api_portal_id=e7010ade-8abc-3e6c-a0f9-4abc53a19df1
    access_link:
    support_email: osmose.coord-gen@ac-dijon.fr
    kind: 'api'
    public: true
    unique: false
    startable_by_applicant: true
    features:
      messaging: true
      transfer: true
      reopening: true
    blocks:
      - name: basic_infos
      - name: legal
      - name: contacts