services_cisirh:
  name: Services et applications fournis par le CISIRH
  description: Le CISIRH contribue à la modernisation de la fonction "ressources humaines" de l’État dans les domaines métiers et applicatifs.
  provider: "cisirh"
  kind: 'service'
  link: "https://services-cisirh.gouv.fr/feedme-with-valid-url"
  cgu_link: "https://services-cisirh.gouv.fr/cgu"
  access_link: "https://services-cisirh.gouv.fr/tokens/%{external_provider_id}"
  public: true
  support_email: "api.cisirh@finances.gouv.fr"
  blocks:
    - name: "basic_infos"
    - name: "scopes"
    - name: "contacts"
  scopes:
    - name: "GA (Gestion administrative)"
      value: "gestion_administrative"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "PLQ (Préliquidation)"
      value: "preliquidation"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "CIR (Interfaces avec le SRE)"
      value: "cir"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "FORM (Formation)"
      value: "formation"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "Congés"
      value: "conges"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "Indemnitaire"
      value: "indemnitaire"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "Portail agent classique (self)"
      value: "portail_agent_classique"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "Portail agent mobile (self-mobile)"
      value: "portail_agent_mobile"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "Mobilité"
      value: "mobilite"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "Listage des entrées"
      value: "listage_entrees"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "GAUdDi"
      value: "gauddi"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "SOCLE RH (mise à disposition de l'extraction des données du partenaire au format SOCLE RH)"
      value: "socle_rh"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "GTA (badgeages, gestion des temps et activités – horaires variables) - Module payant"
      value: "gestion_temps_activites"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "Gestion des moyens - Module payant"
      value: "gestion_moyens"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "API - Module payant"
      value: "api_module_payant"
      group: "RenoiRH, RenoiRH-D et Ingres"
    - name: "RenoiRH-Paie"
      value: "renoirh_paie"
      group: "Autres services et applications"
    - name: "ESTEVE"
      value: "esteve"
      group: "Autres services et applications"
    - name: "SICARDI"
      value: "sicardi"
      group: "Autres services et applications"
    - name: "REBECCA"
      value: "rebecca"
      group: "Autres services et applications"
    - name: "RIGA"
      value: "riga"
      group: "Autres services et applications"
