api-indicateurs-sociaux:
  name:
  description: TODO
  introduction: |
    Ceci est une introduction Ã  remplir
  authorization_request: APIIndicateursSociaux
  steps:
    - name: basic_infos
    - name: legal
    - name: scopes
    - name: personal_data
    - name: contacts
