services-cisirh:
  name: Si vous avez plusieurs formulaires, mettez un nom, sinon supprimer le nom
  description: TODO
  introduction: |
    Ceci est une introduction Ã  remplir
  authorization_request: ServicesCisirh
  steps:
    - name: basic_infos
    - name: legal
    - name: scopes
    - name: personal_data
    - name: contacts
