services-cisirh:
  description: TODO
  introduction: |
    Le présent formulaire a pour objectif de recueillir les différents éléments tant organisationnels que techniques pour le cadrage de la relation entre le CSIRH et ses partenaires.
  authorization_request: ServicesCisirh
  steps:
    - name: basic_infos
    - name: scopes
    - name: contacts
